fn main() {
    // Tell Cargo to re-run this if these env vars change
    println!("cargo:rerun-if-env-changed=FFMPEG_DIR");
    println!("cargo:rerun-if-env-changed=FFMPEG_STATIC");

    // On macOS, link required system libraries for static FFmpeg and set bundle rpath
    #[cfg(target_os = "macos")]
    {
        // Frameworks directory inside the .app bundle
        println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
        println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../lib");

        // System libraries required by static FFmpeg
        println!("cargo:rustc-link-lib=z");
        println!("cargo:rustc-link-lib=bz2");
        println!("cargo:rustc-link-lib=iconv");
    }

    // On Linux AppImage, libs sit next to the binary and link system libraries
    #[cfg(target_os = "linux")]
    {
        println!("cargo:rustc-link-arg=-Wl,-rpath,$ORIGIN/../lib");
        println!("cargo:rustc-link-arg=-Wl,-rpath,$ORIGIN");

        println!("cargo:rustc-link-lib=z");
        println!("cargo:rustc-link-lib=m");
    }

    // FFmpeg static on Windows requires system libraries that vcpkg doesn't automatically pass downstream
    #[cfg(target_os = "windows")]
    {
        println!("cargo:rustc-link-lib=strmiids");
        println!("cargo:rustc-link-lib=ole32");
        println!("cargo:rustc-link-lib=oleaut32");
        println!("cargo:rustc-link-lib=uuid");
        println!("cargo:rustc-link-lib=mfplat");
        println!("cargo:rustc-link-lib=mfuuid");
        println!("cargo:rustc-link-lib=secur32");
        println!("cargo:rustc-link-lib=ws2_32");
        println!("cargo:rustc-link-lib=bcrypt");
        println!("cargo:rustc-link-lib=shlwapi");
        println!("cargo:rustc-link-lib=advapi32");
        println!("cargo:rustc-link-lib=mfreadwrite");
    }

    // Generate canonical_limits.rs into OUT_DIR.
    // Resolution precedence:
    // 1. Versioned package artifact in clypra's node_modules (@clypra-studio/shaders)
    // 2. Sibling monorepo package during local workspace development
    // 3. Local committed limits/gpu-limits.json in src-tauri
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = std::path::Path::new(&out_dir).join("canonical_limits.rs");

    let candidates = [
        "../node_modules/@clypra-studio/shaders/src/gpu-limits.json",
        "../node_modules/@clypra-studio/shaders/gpu-limits.json",
        "../../clypra-packages/packages/shaders/src/gpu-limits.json",
        "limits/gpu-limits.json",
    ];

    let mut resolved_content = None;
    for candidate in &candidates {
        let p = std::path::Path::new(candidate);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", candidate);
            if let Ok(content) = std::fs::read_to_string(p) {
                resolved_content = Some((*candidate, content));
                break;
            }
        }
    }

    let (_source, json_content) = resolved_content.unwrap_or_else(|| {
        (
            "limits/gpu-limits.json",
            include_str!("limits/gpu-limits.json").to_string(),
        )
    });

    let code = format!(
        "// Generated by build.rs — DO NOT EDIT\npub const CANONICAL_LIMITS_JSON: &str = r#\"{}\"#;\n",
        json_content.trim()
    );
    std::fs::write(&dest_path, code).expect("Failed to write canonical_limits.rs");

    tauri_build::build()
}
