allowBuilds:
  canvas: false
  esbuild: false
minimumReleaseAgeExclude:
  - '@clypra-studio/engine@1.4.0 || 1.6.0 || 1.7.0 || 1.8.0 || 1.8.1'
  - '@clypra-studio/shaders@0.2.0'
  - '@clypra-studio/types@0.6.0'
